### ISSUE TITLE
It's not working at all with current hyper.

### ISSUE THREAD

**Issue by urbaniak** [jakubroztocil/httpie-http2#6]
Just after installing httpie-http2 it's not possible to make any request with the following error:

```
http: error: AttributeError: 'module' object has no attribute 'OP_NO_COMPRESSION'
```

Here's the versions:

`````` httpie==0.9.3
httpie-http2==0.0.1
httplib2==0.9.2
hyper==0.5.0```
``````

**Comment by urbaniak** [comment]
I've found that It's caused by old python version with outdated ssl module in OS X.

Closing.

**Comment by sts** [comment]
OSX currently ships Python 2.7.10. [As per documentation](https://docs.python.org/2/library/ssl.html), OP_NO_COMPRESSION should actually be supported in >= 2.7.9, still getting this error.

How did you solve this issue?

**Comment by Lukasa** [comment]
@sts OP_NO_COMPRESSION is not supported in OS X's system Python because Apple ships it linked against OpenSSL 0.9.8zh, which is ancient and does not support the `OP_NO_COMPRESSION` flag at all. OS X's system Python is simply entirely unsuitable for use with HTTP/2, unless you install a PyOpenSSL binary wheel.

**Comment by urbaniak** [comment]
@sts I've installed python from homebrew.

**Comment by try2giveup** [comment]
try this
if not hasattr(ssl, 'OP_NO_COMPRESSION'):
    ssl.OP_NO_COMPRESSION = 131072
